### ISSUE TITLE
float with exch2

### ISSUE THREAD

**Issue by liu-ran** [cspencerjones/float_stuff#1]
Hi, I am pleasantly surprised that your code is about floats with LLC models. I remember the FLT_OPTION.h said this is an 'incomplete implementation'. If we drop some floats into the LLC global simulations, Can we get the correct float trajectories? Many thanks!

Ran

**Comment by cspencerjones** [comment]
Yes, it is possible to run floats in LLC. However, you will need to figure out how to tell the model what the initial position of the floats are. That is why there is "incomplete implementation". Two options are to a) hack flt_init_varia.F or b) write a fake pickup file. Option a) is probably easier.

**Comment by liu-ran** [comment]
Awesome! Many thanks!
